In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=pd.read_csv(r"C:\Users\Vamshitha\Downloads\Position Salary .csv")

In [34]:
df

Position  Level  Salary
0   Busienss Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4  120000
4    Country Manager      5  140000
5     Region Manager      6  130000
6            Partnor      7  100000
7     Senior Partnor      8   90000
8            C Level      9   95000
9               CEO      10   85000

In [10]:
import sklearn
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()


In [28]:
x=df.iloc[:,1:2].values

In [29]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [30]:
y=df.iloc[:,2].values

In [31]:
y

array([ 45000,  50000,  60000, 120000, 140000, 130000, 100000,  90000,
        95000,  85000], dtype=int64)

In [32]:
rf.fit(x,y)

RandomForestRegressor()

In [33]:
y_pred=rf.predict(x)
y_pred

array([ 50200.,  52000.,  60750., 104700., 133700., 131000., 105800.,
        91950.,  93000.,  88200.])

In [35]:
from sklearn.metrics import r2_score
r2_score=r2_score(y,y_pred)
r2_score

0.962904428904429